parameters:
  plugin.isPro: true

services:
  _instanceof:
    Sparkfp\SparkPlugins\SparkWoo\Common\Modules\ModuleInterface:
      tags: ["app.module"]
    Sparkfp\SparkPlugins\SparkWoo\Common\Activation\ActivationHookInterface:
      tags: ["app.activation"]
    Sparkfp\SparkPlugins\SparkWoo\Common\Activation\DeactivationHookInterface:
      tags: ["app.deactivation"]
    Sparkfp\SparkPlugins\SparkWoo\Common\Models\PostModelInterface:
      tags: ["app.postType"]
    Sparkfp\SparkPlugins\SparkWoo\Common\Options\OptionInterface:
      tags: ["app.option"]
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $pluginMeta: "@plugin-meta"
  dismissed-revenue-upgrade-notification-option:
    class: Sparkfp\SparkPlugins\SparkWoo\Common\Options\StringOption
    arguments:
      $prefix: "%plugin.prefix%"
      $name: dismissed_revenue_upgrade_notification
  Sparkfp\SparkPlugins\SparkWoo\ProductRecommendationsFree\Analytics\ThresholdRevenueUpgradeNotificationModule:
    arguments:
      $notificationModule: '@Sparkfp\SparkPlugins\SparkWoo\Common\Notifications\NotificationModule'
      $dismissedOptionMonthly: "@dismissed-revenue-upgrade-notification-option"
      $revenueThreshold: "%notifications.revenueThreshold%"
      $eventRepository: '@Sparkfp\SparkPlugins\SparkWoo\ProductRecommendations\Analytics\AnalyticsEventRepository'
  # shortcode-removed-notification-option:
  #   class: Sparkfp\SparkPlugins\SparkWoo\Common\Options\BooleanOption
  #   arguments:
  #     $prefix: "%plugin.prefix%"
  #     $name: dismissed_shortcode_removed_notification
  # Sparkfp\SparkPlugins\SparkWoo\ProductRecommendationsFree\Shortcodes\RemoveShortcodeFromFreeModule:
  #   arguments:
  #     $productsManager: "@products-manager"
  #     $shortcodeRemovedNotifictionOption: "@shortcode-removed-notification-option"
